apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs-app
  name: nextjs-app
spec:
  selector:
    matchLabels:
      app: nextjsapp
  template:
    metadata:
      labels:
        app: nextjsapp
    spec:
      containers:
        - name: app
          image: us.icr.io/arunmani/ibm_nextjs:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
